kind: reverse
name: mydb
source:
  database: mysql
  conn_str: 'root:12345678@tcp(127.0.0.1:3306)/admin_auth?parseTime=true'
targets:
  - type: codes
    language: golang
    output_dir: ./apps/admin/models/admin